### Create a new patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Thirana Embuldeniya2",
  "email": "thirana2@gmail.com",
  "address": "123 main street22",
  "dateOfBirth": "2000-08-14",
  "registeredDate": "2024-11-28"
}

###