version: "3.8"

services:
  appointment-postgres:
    image: postgres:16
    container_name: appointment-postgres
    environment:
      POSTGRES_DB: appointmentdb
      POSTGRES_USER: admin_viewer
      POSTGRES_PASSWORD: password
    volumes:
      - ./appointment_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - appointment-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_viewer -d appointmentdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  appointment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: appointment-service
    depends_on:
      appointment-postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://appointment-postgres:5432/appointmentdb
      - SPRING_DATASOURCE_USERNAME=admin_viewer
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
    ports:
      - "5000:5000"
    networks:
      - appointment-network
      - microservices-network
    restart: unless-stopped

volumes:
  appointment_postgres_data:

networks:
  appointment-network:
    driver: bridge
  microservices-network:
    external: true
