version: "3.8"

services:
  doctor-postgres:
    image: postgres:16
    container_name: doctor-postgres
    environment:
      POSTGRES_DB: doctordb
      POSTGRES_USER: admin_viewer
      POSTGRES_PASSWORD: password
    volumes:
      - ./doctor_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - doctor-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_viewer -d doctordb"]
      interval: 10s
      timeout: 5s
      retries: 5

  doctor-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: doctor-service
    depends_on:
      doctor-postgres:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://doctor-postgres:5432/doctordb
      - SPRING_DATASOURCE_USERNAME=admin_viewer
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-server:8761/eureka/
    ports:
      - "4000:4000"
    networks:
      - doctor-network
      - microservices-network
    restart: unless-stopped

volumes:
  doctor_postgres_data:

networks:
  doctor-network:
    driver: bridge
  microservices-network:
    external: true
