### POST request to create an appointment
POST http://localhost:5000/appointments
Content-Type: application/json

{
    "patientId": "22222222-2222-2222-2222-222222222222",
    "doctorId": "22222222-2222-2222-2222-222222222222",
    "availabilityId": "bbbb1111-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
    "notes": "Regular checkup"
}